//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace CodeBaseBlog.DomainModel
{
    public partial class Comment
    {
        #region Primitive Properties

        public virtual int Id { get; private set; }

        public virtual string Body { get; private set; }

        public virtual bool Approved { get; private set; }

        public virtual DateTime CreationDate { get; private set; }

        #endregion

        #region Complex Properties

        private UserInfo _user = new UserInfo();

        public virtual UserInfo User
        {
            get { return _user; }
            set { _user = value; }
        }

        #endregion

        #region Navigation Properties

        private Post _post;

        public virtual Post Post
        {
            get { return _post; }
            set
            {
                if (!ReferenceEquals(_post, value))
                {
                    Post previousValue = _post;
                    _post = value;
                    FixupPost(previousValue);
                }
            }
        }

        #endregion

        #region Association Fixup

        private void FixupPost(Post previousValue)
        {
            if (previousValue != null && previousValue.Comments.Contains(this))
            {
                previousValue.Comments.Remove(this);
            }

            if (Post != null)
            {
                if (!Post.Comments.Contains(this))
                {
                    Post.Comments.Add(this);
                }
            }
        }

        #endregion
    }
}