//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBaseBlog.DomainModel
{
    public partial class UserInfo
    {
        #region Primitive Properties

        public string Name { get; private set; }

        public string Email { get; private set; }

        public string WebSite { get; private set; }

        public string UserId { get; set; }

        #endregion
    }
}